services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./session:/app/session
      - ./data:/app/data
      - ./reports:/app/reports
    stdin_open: true
    tty: true

  api:
    build: .
    container_name: tfg_api
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./reports:/app/reports
      - ./docs:/app/docs
    command: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: tfg_grafana
    restart: always
    depends_on:
      - api
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  grafana_data:
