apiVersion: 1

datasources:
  - name: TFG-API
    uid: tfg_api
    type: marcusolsson-json-datasource
    access: proxy
    url: http://api:8000
    isDefault: true
    editable: true
    jsonData:
      httpHeaderName1: X-API-Key
    secureJsonData:
      httpHeaderValue1: ${API_KEY}
